### ISSUE TITLE
Porting to Python3, running into a problem.

### ISSUE THREAD

**Issue by jondthompson** [nutechsoftware/alarmdecoder-webapp#95]
So I've given up on getting this running on Bullseye without doing a bunch of work and porting it to Python3. 

Anyhow, I'm now stuck trying to figure out this traceback when I run "flask run" or "flask route"...

```
pi@AlarmDecoder:/opt/alarmdecoder-webapp $ flask routes
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/pi/.local/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/pi/.local/lib/python3.9/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/pi/.local/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/opt/alarmdecoder-webapp/wsgi.py", line 29, in <module>
    from ad2web import create_app, init_app
  File "/opt/alarmdecoder-webapp/ad2web/__init__.py", line 1, in <module>
    from .app import create_app
  File "/opt/alarmdecoder-webapp/ad2web/app.py", line 18, in <module>
    from .decoder import decodersocket, Decoder, create_decoder_socket
  File "/opt/alarmdecoder-webapp/ad2web/decoder.py", line 37, in <module>
    from .notifications import NotificationSystem, NotificationThread
  File "/opt/alarmdecoder-webapp/ad2web/notifications/__init__.py", line 4, in <module>
    from .views import notifications
  File "/opt/alarmdecoder-webapp/ad2web/notifications/views.py", line 9, in <module>
    from ad2web.settings import Setting
  File "/opt/alarmdecoder-webapp/ad2web/settings/__init__.py", line 4, in <module>
    from .views import settings
  File "/opt/alarmdecoder-webapp/ad2web/settings/views.py", line 47, in <module>
    from .forms import ProfileForm, PasswordForm, ImportSettingsForm, HostSettingsForm, EthernetSelectionForm, EthernetConfigureForm, SwitchBranchForm, EmailConfigureForm, UPNPForm, VersionCheckerForm, ExportConfigureForm
  File "/opt/alarmdecoder-webapp/ad2web/settings/forms.py", line 22, in <module>
    from .constants import DAILY, WEEKLY, MONTHLY, NONE
  File "/opt/alarmdecoder-webapp/ad2web/settings/constants.py", line 3, in <module>
    from setup.constants import NETWORK_DEVICE, SERIAL_DEVICE
  File "/opt/alarmdecoder/setup.py", line 20, in <module>
    long_description=readme(),
  File "/opt/alarmdecoder/setup.py", line 9, in readme
    with open('README.rst') as readme_file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```
What I can't figure out is how the call to ```setup.constants import NETWORK_DEVICE, SERIAL_DEVICE``` is resulting in the setup.py for /opt/alarmdecoder getting run...

**Comment by jondthompson** [comment]
Nevermind.  Thanks for being the ducky on the desk...

(I needed to change the setup.constants to ad2web.setup.constants.)

**Comment by omriasta** [comment]
Were yo uever able to get this ported to python3? I started trying but ran into a bunch of issues myself...wondering if you have a working fork of this?
